modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Merpig/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-merpig"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="merpig" #mandatory
version="0.0.1" #mandatory
displayName="[SBM] Merpig" #mandatory
description='''Ridable sea creature''' #mandatory

[[dependencies.merpig]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.merpig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"