modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Merpig/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-merpig"
license="MIT License https://github.com/BuiltBrokenModding/SBM-Merpig/blob/1.16/LICENSE"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="merpig" #mandatory
version="0.0.1" #mandatory
displayName="[SBM] Merpig" #mandatory
description='''Ridable sea creature''' #mandatory

[[dependencies.merpig]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.merpig]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"